name: Auto Bump Version

on:
  push:
    branches: [ main ]
    paths:
      - 'arcompile_version.py'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extraer y aumentar versión
      run: |
        VERSION_LINE=$(grep "__version__" arcompile_version.py)
        VERSION=$(echo "$VERSION_LINE" | cut -d '"' -f2)
        echo "Versión actual: $VERSION"

        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        NEW_VERSION="$MAJOR.$MINOR.$((PATCH+1))"

        echo "Nueva versión: $NEW_VERSION"
        echo "__version__ = \"$NEW_VERSION\"" > arcompile_version.py

    - name: Commit si hay cambios
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add arcompile_version.py
        git diff --cached --quiet || git commit -m "⬆ Bump version to $NEW_VERSION"
        git push
