name: bump-version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo con historial completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Detectar si el último commit fue un bump
        id: check-bump
        run: |
          LAST_MSG=$(git log -1 --pretty=%B)
          echo "Último commit: '$LAST_MSG'"
          if [[ "$LAST_MSG" == Bump\ version\ to* ]]; then
            echo "bump=true" >> $GITHUB_OUTPUT
          else
            echo "bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Extraer y aumentar versión
        if: steps.check-bump.outputs.bump == 'false'
        id: version
        run: |
          file="arcompile_version.py"
          current=$(grep -oP '__version__\s*=\s*"\K[0-9.]+' "$file")
          echo "Versión actual: $current"
          IFS='.' read -r major minor patch <<< "$current"
          patch=$((patch + 1))
          new="$major.$minor.$patch"
          echo "__version__ = \"$new\"" > "$file"
          echo "Nueva versión: $new"
          echo "version=$new" >> $GITHUB_OUTPUT

      - name: Commit y push bump
        if: steps.check-bump.outputs.bump == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add arcompile_version.py
          git commit -m "Bump version to ${{ steps.version.outputs.version }}" || echo "Nada que commitear"
          git push origin HEAD:main
