name: bump-version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Cancelar si último commit fue de bump
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT_MSG" == Bump\ version\ to* ]]; then
            echo "Último commit fue un bump de versión, cancelando..."
            exit 0
          fi

      - name: Extraer y aumentar versión
        if: steps.check-bump.outputs.bump == 'false'
        id: version
        run: |
          version_file="arcompile_version.py"
          current_version=$(grep -oP '__version__\s*=\s*"\K[0-9.]+' "$version_file")
          echo "Versión actual: $current_version"

          IFS='.' read -r major minor patch <<< "$current_version"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "Nueva versión: $new_version"

          echo "__version__ = \"$new_version\"" > "$version_file"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit si hay cambios
        if: steps.check-bump.outputs.bump == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump version to ↑ ${{ steps.version.outputs.version }} ↑" || exit 0
          git push origin HEAD:main
